version: '3.1'

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./db:/var/lib/postgresql/data
  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    container_name: backend
    command: sh -c "npm run dev"
    ports:
      - 8000:3000
    volumes:
      - './backend:/backend'
    environment:
      - LANG=C.UTF-8
      - PYTHONIOENCODING=utf8
      - ENV=development
      - COMMIT_SHA1=development
      - DB_HOST=db
      - DB_PORT=3306
      - DATABASE_CREATION=create_preset_data
    depends_on:
      - db
    tty: true
