version: '3.1'

services:
  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    container_name: backend
    command: sh -c "npm run dev"
    ports:
      - 8000:3000
      - 5555:5555
    volumes:
      - './backend:/backend'
    env_file:
      - .env
    environment:
      - LANG=C.UTF-8
      - PYTHONIOENCODING=utf8
      - ENV=development
      - COMMIT_SHA1=development
      - DB_HOST=db
      - DB_PORT=3306
      - DATABASE_CREATION=create_preset_data
    tty: true
