name: Run frontend tests

on:
  push:
    paths:
      - 'frontend/src/**'
  # pull_request:
  #   branches: [ main ]

defaults:
  run:
    shell: bash
    working-directory: frontend

jobs:
  migration:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [10.x, 12.x, 14.x, 15.x]
    #     with:
    #       node-version: ${{ matrix.node-version }}
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "17.x"
        # with:
        #   node-version: ${{ matrix.node-version }}

      - name: CI BUILD TEST ✅
        run: |
          npm ci
          npm run build --if-present
          npm test
